---

#########################INSTALL PACKAGES#########################

- name: Update package lists
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - software-properties-common
      - ca-certificates
      - lsb-release
      - apt-transport-https
      - curl
      - git
      - software-properties-common
      - apache2
      - postgresql-14
    state: present

- name: Add PHP PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP 8.2
  apt:
    name: php8.2
    state: present

- name: Install additional PHP modules
  apt:
    name:
      - php8.2-cli
      - php8.2-common
      - php8.2-fpm
      - php8.2-pgsql
      - php8.2-zip
      - php8.2-gd
      - php8.2-mbstring
      - php8.2-curl
      - php8.2-xml
      - php8.2-bcmath
      - php8.2-intl
      - php8.2-dom
    state: present
    update_cache: yes

- name: Install Composer version 2.6.6
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.6.6"

- name: Install key for nodejs
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
    filename: nodesource

- name: Install Node.js
  apt:
    name: nodejs
    state: present

